### PR TITLE
Specify standard test in PackageInfo.g

### PR DESCRIPTION
**Pull request by olexandr-konovalov**
This completes #4.

### CODE REVIEW

**Comment by olexandr-konovalov** [comment]
In the meantime, new version has been picked up (hence, this PR would require a new release):
```
* matgrp - new version 0.5 discovered!!!
  ============================================
  Getting new archives from 
  http://www.math.colostate.edu/~hulpke/matgrp/matgrp0.5[ ".tar.gz" ]
  unpacking matgrp0.5.tar.gz
  Validation of the info file successful!
  Package matgrp 0.5 from 10/09/2018 has dependencies:
  * NeededOtherPackages [ [ "recog", ">= 1.2" ], [ "Forms", ">= 1.2" ], 
  [ "genss", ">= 1.3" ], [ "Orb", ">= 3.4" ], [ "AtlasRep", ">= 1.4.0" ] ]
  * GAP >=4.7
  finding text files  . . .

=====================text files==========================
matgrp/PackageInfo.g
matgrp/init.g
matgrp/read.g
matgrp/README.md
matgrp/lib/recograt.gd
matgrp/lib/recograt.gi
matgrp/htm/indxE.htm
matgrp/htm/indxG.htm
matgrp/htm/chapters.htm
matgrp/htm/indxU.htm
matgrp/htm/biblio.htm
matgrp/htm/indxM.htm
matgrp/htm/theindex.htm
matgrp/htm/CHAP001.htm
matgrp/doc/._matgrp.tex
matgrp/doc/matgrp.tex
matgrp/doc/._manual.tex
matgrp/doc/manual.tex
matgrp/tst/basic.tst
matgrp/tst/testall.g

=====================end of the list of text files=======
=====================binary files========================
matgrp/doc/manual.ind
matgrp/doc/manual.pdf
matgrp/doc/manual.six
matgrp/doc/manual.bbl

=====================end of the list of binary files=====
=====================ignored files=======================

=====================end of the list of ignored files====
removing pkg/matgrp/README
removing pkg/matgrp/doc/._manual.pdf
removing pkg/matgrp/doc/gapmacro.tex
removing pkg/matgrp/doc/manual.aux
adding pkg/matgrp/doc/manual.bbl
removing pkg/matgrp/doc/manual.example-1.tst
removing pkg/matgrp/doc/manual.idx
adding pkg/matgrp/doc/manual.ind
removing pkg/matgrp/doc/manual.lab
removing pkg/matgrp/doc/manual.log
removing pkg/matgrp/doc/manual.toc
  ============================================
```

**Comment by olexandr-konovalov** [comment]
I was surprised to see that tests pass in MatGrp despite I remember that I've submitted this PR but is has not been merged and no new release of MatGrp has been made. I had to investigate that, because definitely I do not perform any automated testing for tests lying around unless they are specified in PackageInfo.g. It happened that the released version of the file actually contained the line `TestFile := "tst/testall.g",` but apparently it was not committed to the repository.  Please either commit your local copy and close my PR, or merge my PR and abandon your modification in the file, whatever is easier.

**Comment by olexandr-konovalov** [comment]
P.S. In particular, test of this repository (which tests the clone, instead of the released version) at https://travis-ci.org/gap-packages/gap-docker-pkg-tests-master-devel/jobs/427920755 fails with

    #I No standard tests specified in matgrp package, version 0.5

**Comment by olexandr-konovalov** [comment]
@hulpke Could you please deal with this issue - otherwise, it is not possible to test this repository with GAP in the test at 
https://travis-ci.org/gap-packages/gap-docker-pkg-tests-master-devel/jobs/429355398 - it fails with
```
#I No standard tests specified in matgrp package, version 0.5
```

**Comment by hulpke** [comment]
@alex-konovalov 
Yes, for some reason I forgot to put the last change of the file in place. Its changed now (should pick up version 0.51)

**Pull request merged**
